services:
  gateway:
    image: nginx:latest
    container_name: gateway
    ports:
      - "80:80"
    volumes:
      - ./gateway/nginx.conf:/etc/nginx/nginx.conf:ro
      - frontend_build:/usr/share/nginx/html:ro
    depends_on:
      - frontend
      - backend
      - ai-service

  frontend:
    build: ./frontend
    container_name: frontend
    volumes:
      - frontend_build:/usr/share/nginx/html:ro

  backend:
    build: ./backend
    container_name: backend
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: realtime_db
      DB_PORT: 5432
    depends_on:
      - db

  ai-service:
    build: ./ai-service
    container_name: ai-service

  db:
    image: postgres:16-alpine
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: realtime_db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
  frontend_build:

